

3.	FROM debian:9.5-slim
4.	
5.	
6.	
7.	LABEL "com.github.actions.name"="Hello World"
8.	
9.	LABEL "com.github.actions.description"="Write arguments to the standard output"
10.	
11.	LABEL "com.github.actions.icon"="mic"
12.	
13.	LABEL "com.github.actions.color"="purple"
14.	
15.	
16.	
17.	LABEL "repository"="http://github.com/octocat/hello-world"
18.	
19.	LABEL "homepage"="http://github.com/actions"
20.	
21.	LABEL "maintainer"="Octocat <octocat@github.com>"
22.	
23.	
24.	
25.	ADD entrypoint.sh /entrypoint.sh
26.	
27.	RUN chmod +x /entrypoint.sh
28.	
    ENTRYPOINT ["/entrypoint.sh"]


